logging:
  level:
    root: INFO
    com.order.service: DEBUG
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Priya@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Options: none, validate, update, create, create-drop
    show-sql: true # Shows SQL statements in the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect    
server:
  port: 8081        